### ISSUE TITLE
is support vue3?

### ISSUE THREAD

**Issue by huangche007** [xfy196/virtual-list-scroll#1]
hi，I wanna konw  whether `virtual-list-scroll`  support vue3?

**Comment by xfy196** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        hi, Virtual list scroll does not support vue3.0 for the time being, and the version of vue3.0 will be added later。
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xfy196
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 06/15/2021 ***@***.***> wrote： 




hi，I wanna konw  whether virtual-list-scroll  support vue3?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
